[[mounts]]
  source = "node_modules/@hyas/core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/core/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/gethyas/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/seo/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/images/assets"
  target = "assets"
  excludeFiles = "/scss/**.scss"

[[mounts]]
  source = "node_modules/@hyas/images/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/bolt-core/archetypes"
  target = "archetypes"

[[mounts]]
  source = "node_modules/@hyas/bolt-core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/bolt-core/layouts"
  target = "layouts"

[[mounts]]
  source = "themes/my-bolt-theme/archetypes"
  target = "archetypes"

[[mounts]]
  source = "themes/my-bolt-theme/assets"
  target = "assets"

[[mounts]]
  source = "themes/my-bolt-theme/layouts"
  target = "layouts"

[[mounts]]
  source = "archetypes"
  target = "archetypes"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "content"
  target = "content"

[[mounts]]
  source = "data"
  target = "data"

[[module.mounts]]
  source = "i18n"
  target = "i18n"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "static"
  target = "static"
