# Images (@hyas/images)
[image]
  ## General
  type = "page"
  widths = [ 480, 640, 768, 1_024, 1_366 ]
  densities = [ 1, 2 ]
  formats = [ "original", "webp" ]
  loading = "lazysizes"
  class = "img-fluid blur-up"
  output = "picture"
  noscript = false

  ## Placeholder
  placeholder = "lqip"
  lqip_div_factor = 5
  lqip_blur_amount = 5
  gif_div_factor = 10

  ## Figure
  target = "_blank"
  rel = "noopener, noreferrer"
  figure_class = "figure"
  figure_image_class = "figure-img img-fluid blur-up"
  figcaption_class = "figure-caption"
  figcaption_title_h = 4
  attr_link_target = "_blank"
  attr_link_rel = "noopener, noreferrer"

  ## Render hook
  render_hook = true
  render_hook_wrapper_class = "img-wrapper"

  ## Shortcode
  shortcode_wrapper_class = "img-wrapper"
  suppress_width_warning = false

  ## Debugging
  debug = false

# Inline SVG (@hyas/inline-svg)
[inline_svg]
  icon_set_dir = "tabler-icons"

# SEO (@hyas/seo)
[seo]
  description = "Doks is a Hyas theme for building custom, production-ready documentation websites."
  og_article_types = [
    "post",
    "posts",
    "blog",
    "news",
    "article",
    "articles",
    "event",
    "events",
    "course",
    "courses"
  ]
  jsonld_article_types = [ "article", "articles" ]
  jsonld_news_article_types = [ "news", "updates" ]
  jsonld_blog_posting_types = [ "post", "posts", "blog" ]
  image = "/images/hyas-schema-image.png"
  private = false

  [seo.generate]
    title = true
    meta = true
    twitter = true
    og = true
    [seo.generate.jsonld]
      article = true
      breadcrumbs = true

  [seo.title_tag]
    separator = "|"
    home_text = "Modern Documentation Theme"
